### ISSUE TITLE
Virtual Methods example doesn't link

### ISSUE THREAD

**Issue by timmyjose** [rougier/CPP-Crash-Course#5]
Location: https://github.com/rougier/CPP-Crash-Course?tab=readme-ov-file#virtual-methods

Issue: With `virtual void method2( void );`, the example will fail at the linking stage. 

Fix: Either declare it purely virtual: `virtual void method2( void ) = 0;`, or provide a definition for `method2` in `Base`.

**Comment by rougier** [comment]
Thanks, can you make a PR?

**Comment by timmyjose** [comment]
Hey @rougier, I actually looked at this while creating the other PR. It is possible that the example I was trying may not be exactly in line with the intent of the section in the tutorial.

I'll double-check that, and if applicable still, open a PR, otherwise will close this issue. 👍
